services:
  frontend:
    container_name: app_frontend
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    working_dir: /front-end
    healthcheck:
      test: ["CMD-SHELL", "lsof -t -i:3000 || exit 1"]
      timeout: 10s
      retries: 5
  backend:
    container_name: app_backend
    build:
      context: ./back-end/rdv
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    working_dir: /app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_HOST=localhost
      - DB_PORT=5440
      - DB_NAME=rdvDB
      - DB_USERNAME=postgres
    healthcheck:
      test: ["CMD-SHELL", "lsof -t -i:8080 || exit 1"]
      timeout: 10s
      retries: 5
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost", "-p", "5432"]
      timeout: 10s
      retries: 5

